steps:
  - name: "gcr.io/cloud-builders/npm"
    dir: "frontend"        # Tambahkan ini supaya npm jalan di folder frontend
    entrypoint: "bash"
    args:
      - "-c"
      - |
        if [ ! -d "node_modules" ]; then
          echo "Installing dependencies..."
          npm ci
        else
          echo "Skipping npm install, node_modules exists."
        fi

  - name: "gcr.io/cloud-builders/npm"
    dir: "frontend"        # Tambahkan ini supaya npm run build di folder frontend
    entrypoint: "bash"
    args:
      - "-c"
      - |
        npm run build

  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    args: ["app", "deploy", "--quiet"]

options:
  logging: CLOUD_LOGGING_ONLY
