GET  https://proyekakhirpraktcc-174534490336.us-central1.run.app/api/users

### REGISTER USER
POST https://proyekakhirpraktcc-174534490336.us-central1.run.app/api/users/register
Content-Type: application/json

{
  "name": "pipi",
  "email": "pipi@gmail.com",
  "phone": "08123456789",
  "password": "pipi",
  "role": "user"
}

###
POST https://proyekakhirpraktcc-174534490336.us-central1.run.app/api/users/login
Content-Type: application/json

{
  "email": "pipi@gmail.com",
  "password": "pipi"
}

### GET ALL USERS
GET https://proyekakhirpraktcc-174534490336.us-central1.run.app/api/users/

### CREATE HOTEL
POST https://proyekakhirpraktcc-174534490336.us-central1.run.app/
Content-Type: application/json

{
  "name": "Hotel Surya",
  "address": "Jl. Merdeka No.1",
  "price_per_night": 500000,
  "facilities": "WiFi, AC, Breakfast",
  "rooms_available": 10,
  "image_url": "http://example.com/image.jpg"
}

### GET ALL HOTELS
GET https://proyekakhirpraktcc-174534490336.us-central1.run.app/hotels

### UPDATE HOTEL (misal id = 1)
PUT https://proyekakhirpraktcc-174534490336.us-central1.run.app/1
Content-Type: application/json

{
  "price_per_night": 550000,
  "rooms_available": 8
}

### DELETE HOTEL (misal id = 1)
DELETE https://proyekakhirpraktcc-174534490336.us-central1.run.app/1

### CREATE BOOKING
POST https://proyekakhirpraktcc-174534490336.us-central1.run.app/createbooking
Content-Type: application/json

{
  "user_id": 1,
  "hotel_id": 1,
  "guest_name": "Test Guest",
  "guest_email": "guest@example.com",
  "guest_phone": "08123456789",
  "room_type": "Deluxe",
  "check_in_date": "2025-06-10",
  "check_out_date": "2025-06-15",
  "total_price": 2500000
}

### GET ALL BOOKINGS
GET https://proyekakhirpraktcc-174534490336.us-central1.run.app/hotels
